events {
    worker_connections 1024;
}

http {
    # Reference the 15-year static Cloudflare keys globally
    ssl_certificate     /etc/nginx/certs/cloudflare.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    # Modern TLS standards required by Cloudflare edge nodes
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

}
