###################
# - VPS - #
###################
name: vps-wordpress

############
# Services #
############
services:
    portainer:
        container_name: vps-portainer
        image: portainer/portainer-ce:sts
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./volumes/portainer:/data
        ports:
            - 9443:9443
#      - 8000:8000  # Remove if you do not intend to use Edge Agents

    db:
        container_name: vps-db
        image: mysql:8
        restart: always
        env_file: .env
        volumes:
            - ./volumes/mysql8:/var/lib/mysql
            - ./configs/mysql/performance.cnf:/etc/mysql/conf.d/performance.cnf

    phpmyadmin:
        container_name: vps-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
#            MYSQL_ROOT_PASSWORD: db_root_password
        ports:
            - "8080:80"
        volumes:
            - ./configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    wordpress:
        container_name: vps-wordpress
        image: wordpress
        restart: always
        depends_on:
            - db
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
            WORDPRESS_DB_USER: ${MYSQL_USER:-wp_user}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wp_pass}
        volumes:
            - ./volumes/wordpress:/var/www/html
            - ./configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
